version: '3.8'

services:
  app:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api

  mongo:
    image: mongo
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  
  redis:
    image: redis
    container_name: redis-server
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  server:
    image: todo-backend
    container_name: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis-server:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo-server:27017/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy